#!/bin/bash

export ASPNETCORE_ENVIRONMENT=NONSENSE_VALUE
export NoteTaker__NotificationService__SendGrid__ApiKey=NONSENSE_VALUE
export ConnectionStrings__NoteTakerService=NONSENSE_VALUE
export ConnectionStrings__NoteTakerTest=NONSENSE_VALUE